### ISSUE TITLE
Great plugin!, but fails on etherscan-verify

### ISSUE THREAD

**Issue by iangregsondev** [wighawag/hardhat-preprocessor#12] opened 2021-07-11 16:16 UTC
Hi,

Great plugin, although etherscan fails - i presume this is because etherscan-verify plugin isn't in the same pipeline or something so it doesn't get run - so hence the files are different ?

The only thing I was doing was removing "console.log"

```
  preprocess: {
    eachLine: removeConsoleLog((hre) => hre.network.name !== 'hardhat' && hre.network.name !== 'localhost'),
  },
```

This is the error (npx hardhat etherscan-verify --network bsc_mainnet)

```
Failed to verify contract Token: NOTOK, Fail - Unable to verify
{
  "apikey": "XXXXXX",
  "module": "contract",
  "action": "verifysourcecode",
```

**Comment by wighawag** [comment] 2021-07-11 16:57
Thanks for the report.

That could be a problem with etherscan-verify.

If you use hardhat-deploy that include a task to verify contract on etherscan and sourcify it should work

**Comment by iangregsondev** [comment] 2021-07-11 17:04
Thanks for the quick response.

Actually, I am using hardhat-deploy, and I think I am doing it right

https://github.com/wighawag/hardhat-deploy#4-hardhat-etherscan-verify

But it fails.

I am doing 

```
 npx hardhat deploy --network bsc_mainnet

and then..

 npx hardhat etherscan-verify --network bsc_mainnet

```

**Comment by wighawag** [comment] 2021-07-12 07:11
That could be something else, as hardhat-deploy etherscan-verify use the
metadata outputed by the compiler used for deployment. It should thus be
exactly same. You can look up the source in the metadata field of your
deployed contract ( in the deployments/bsc_mainnet folder) and see if your
preprocessing was applied there.

**Comment by Shelvak** [comment] 2021-11-14 00:50
I was creating an issue in hardhat before discover that pre-process was _the problem_. I use the plugin to change addresses from test to mainnet/testnet. At least for me the verify process verifies the contract but with all the project files. I use tenderly too to verify with:
```javascript
const contract = await (await hre.ethers.getContractFactory('UniZap')).deploy()
await contract.deployed();
await hre.tenderly.verify({ name: 'UniZap', address: contract.address }) 15 files verified (as expected)
await hre.run('verify:verify', { address: contract.address, contract: `contracts/UniZap.sol:UniZap` }) # 51 files verified
```
https://mumbai.polygonscan.com/address/0xd107ab4fb0ca23ad2e4e99017dfc73e567a246ef#code #  51 files verified
https://dashboard.tenderly.co/contract/mumbai/0xd107ab4fb0ca23ad2e4e99017dfc73e567a246ef/source # 15 files verified as expected

If I comment the preprocess lines in my hardhat config the verify line works as expected. 
I can verify my contracts with "single file" changing manually the addresses too... 
https://mumbai.polygonscan.com/address/0xa067f8559462594521af6ce3bb0658beb33078e4#code (single file manual verification)

**Comment by wighawag** [comment] 2021-11-14 08:01
As my comment above state, if you use hardhat-deploy's builtin verification task: `etherscan-verify` it should work

You are using thrird party tools that are attempting to recompile the contract to get the bytecode not ensuring you, you did not change the code since last deployment

I would create an issue on their side as their tool will be affected by any plugin that preprocess source code. hardhat-deploy etherscan-verify is not affected.

**Comment by fedealconada** [comment] 2022-11-10 11:41
@wighawag I was having this same issue and using the built-in verification task made the trick BUT I had too use the `--solc-input` param (which I'm not supposed to since I'm using `0.8.13`. 
Also, after verifying, I'm getting this warning:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/4473536/201081711-734ca331-9565-4f2a-acf9-7c8ef4e2f86d.png">
Any idea?

**Comment by wighawag** [comment] 2022-11-30 16:44
I am closing this as the issue is about hardhat-preprocessor
see : https://github.com/wighawag/hardhat-deploy/issues/78#issuecomment-1310170681

**Closed by wighawag** 2022-11-30 16:44 UTC
